name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest] #, windows-latest]
        example: [examples/platformio_example.c]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade platformio

    - name: Run PlatformIO
      run: pio ci --lib="." --board=pico
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}

