# Sets up the development environment
version: "3.2"
services: 
    proxy:
        restart: always
        build:
            dockerfile: dev.Dockerfile
            context: ./proxy
        ports:
            - "3050:80"
        networks:
            - app-network
        hostname: proxy
        container_name: shabam_proxy
        depends_on: 
            - "api"
            - "client"
            - "fingerprint_worker"
            - "identification_worker"
    api:
        build:
            dockerfile: dev.Dockerfile
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            # Main DB
            - "PG_MAIN_HOST=${SHABAM_PG_MAIN_HOST}"
            - "PG_MAIN_DATABASE=${SHABAM_PG_MAIN_DATABASE}"
            - "PG_MAIN_USER=${SHABAM_PG_MAIN_USER}"
            - "PG_MAIN_PORT=${SHABAM_PG_MAIN_PORT}"
            - "PG_MAIN_PASSWORD=${SHABAM_PG_MAIN_PASSWORD}"
            # Address 1 DB
            - "PG_ADR1_HOST=${SHABAM_PG_ADR1_HOST}"
            - "PG_ADR1_DATABASE=${SHABAM_PG_ADR1_DATABASE}"
            - "PG_ADR1_USER=${SHABAM_PG_ADR1_USER}"
            - "PG_ADR1_PORT=${SHABAM_PG_ADR1_PORT}"
            - "PG_ADR1_PASSWORD=${SHABAM_PG_ADR1_PASSWORD}"
            # Address 2 DB
            - "PG_ADR2_HOST=${SHABAM_PG_ADR2_HOST}"
            - "PG_ADR2_DATABASE=${SHABAM_PG_ADR2_DATABASE}"
            - "PG_ADR2_USER=${SHABAM_PG_ADR2_USER}"
            - "PG_ADR2_PORT=${SHABAM_PG_ADR2_PORT}"
            - "PG_ADR2_PASSWORD=${SHABAM_PG_ADR2_PASSWORD}"
            # Address 3 DB
            - "PG_ADR3_HOST=${SHABAM_PG_ADR3_HOST}"
            - "PG_ADR3_DATABASE=${SHABAM_PG_ADR3_DATABASE}"
            - "PG_ADR3_USER=${SHABAM_PG_ADR3_USER}"
            - "PG_ADR3_PORT=${SHABAM_PG_ADR3_PORT}"
            - "PG_ADR3_PASSWORD=${SHABAM_PG_ADR3_PASSWORD}"
            # Misc
            - "ADDRESS_DB_COUNT=3"
            - "JWT_SECRET=${SHABAM_JWT_SECRET}"
            - "JWT_EXPIRE_TIME=${SHABAM_JWT_EXPIRE_TIME}"
        networks:
            - app-network
        hostname: api
        container_name: shabam_api
    client:
        build:
            dockerfile: dev.Dockerfile
            context: ./client
        volumes: 
            - /app/node_modules
            - /root
            - ./client:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true
        networks:
            - app-network
        privileged: true
        container_name: shabam_client
    fingerprint_worker:
        build:
            dockerfile: dev.Dockerfile
            context: ./fingerprint_worker
        volumes: 
            - /app/node_modules
            - ./fingerprint_worker:/app
        networks:
            - app-network
        hostname: fingerprint_worker
        container_name: shabam_fingerprint_worker
    identification_worker:
        build:
            dockerfile: dev.Dockerfile
            context: ./identification_worker
        volumes: 
            - /app/node_modules
            - ./identification_worker:/app
        networks:
            - app-network
        hostname: identification_worker
        container_name: shabam_identification_worker
    records_worker:
        build:
            dockerfile: dev.Dockerfile
            context: ./records_worker
        volumes:
            - /app/node_modules
            - ./records_worker:/app
        environment:
            # Address 1 DB
            - "PG_ADR1_HOST=${SHABAM_PG_ADR1_HOST}"
            - "PG_ADR1_DATABASE=${SHABAM_PG_ADR1_DATABASE}"
            - "PG_ADR1_USER=${SHABAM_PG_ADR1_USER}"
            - "PG_ADR1_PORT=${SHABAM_PG_ADR1_PORT}"
            - "PG_ADR1_PASSWORD=${SHABAM_PG_ADR1_PASSWORD}"
            # Address 2 DB
            - "PG_ADR2_HOST=${SHABAM_PG_ADR2_HOST}"
            - "PG_ADR2_DATABASE=${SHABAM_PG_ADR2_DATABASE}"
            - "PG_ADR2_USER=${SHABAM_PG_ADR2_USER}"
            - "PG_ADR2_PORT=${SHABAM_PG_ADR2_PORT}"
            - "PG_ADR2_PASSWORD=${SHABAM_PG_ADR2_PASSWORD}"
            # Address 3 DB
            - "PG_ADR3_HOST=${SHABAM_PG_ADR3_HOST}"
            - "PG_ADR3_DATABASE=${SHABAM_PG_ADR3_DATABASE}"
            - "PG_ADR3_USER=${SHABAM_PG_ADR3_USER}"
            - "PG_ADR3_PORT=${SHABAM_PG_ADR3_PORT}"
            - "PG_ADR3_PASSWORD=${SHABAM_PG_ADR3_PASSWORD}"
            # Misc
            - "ADDRESS_DB_COUNT=3"
        networks:
            - app-network
        hostname: records_worker
        container_name: shabam_records_worker
networks:
    app-network: