# Sets up the development environment but with the client production image running
version: "3.2"
services: 
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3050:80"
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - "PG_HOST=${SHABAM_PG_HOST}"
            - "PG_DATABASE=${SHABAM_PG_DATABASE}"
            - "PG_USER=${SHABAM_PG_USER}"
            - "PG_PORT=${SHABAM_PG_PORT}"
            - "PG_PASSWORD=${SHABAM_PG_PASSWORD}"
    client:
        build:
            dockerfile: Dockerfile
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app