# Sets up the development environment
version: "3.2"
services: 
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3050:80"
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - "PG_HOST=${SHABAM_PG_HOST}"
            - "PG_DATABASE=${SHABAM_PG_DATABASE}"
            - "PG_USER=${SHABAM_PG_USER}"
            - "PG_PORT=${SHABAM_PG_PORT}"
            - "PG_PASSWORD=${SHABAM_PG_PASSWORD}"
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true
    fingerprint_worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./fingerprint_worker
        volumes: 
            - /app/node_modules
            - ./fingerprint_worker:/app