# Sets up the development environment
version: "3.2"
services: 
    proxy:
        restart: always
        build:
            dockerfile: dev.Dockerfile
            context: ./proxy
        ports:
            - "3050:80"
        networks:
            - app-network
        hostname: proxy
        container_name: shabam_proxy
        depends_on: 
            - "api"
            - "client"
            - "fingerprint_worker"
            - "identification_worker"
    api:
        build:
            dockerfile: dev.Dockerfile
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - "PG_HOST=${SHABAM_PG_HOST}"
            - "PG_DATABASE=${SHABAM_PG_DATABASE}"
            - "PG_USER=${SHABAM_PG_USER}"
            - "PG_PORT=${SHABAM_PG_PORT}"
            - "PG_PASSWORD=${SHABAM_PG_PASSWORD}"
            - "JWT_SECRET=${SHABAM_JWT_SECRET}"
            - "JWT_EXPIRE_TIME=${SHABAM_JWT_EXPIRE_TIME}"
        networks:
            - app-network
        hostname: api
        container_name: shabam_api
    client:
        build:
            dockerfile: dev.Dockerfile
            context: ./client
        volumes: 
            - /app/node_modules
            - /root/.emscripten_cache
            - ./client:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true
            - "PLOTLY_API_USERNAME=${SHABAM_PLOTLY_API_USERNAME}"
            - "PLOTLY_API_KEY=${SHABAM_PLOTLY_API_KEY}"
        networks:
            - app-network
        privileged: true
        container_name: shabam_client
    fingerprint_worker:
        build:
            dockerfile: dev.Dockerfile
            context: ./fingerprint_worker
        volumes: 
            - /app/node_modules
            - ./fingerprint_worker:/app
        networks:
            - app-network
        hostname: fingerprint_worker
        container_name: shabam_fingerprint_worker
    identification_worker:
        build:
            dockerfile: dev.Dockerfile
            context: ./identification_worker
        volumes: 
            - /app/node_modules
            - ./identification_worker:/app
        networks:
            - app-network
        hostname: identification_worker
        container_name: shabam_identification_worker
networks:
    app-network: