# Sets up the development environment but with the client production image running
version: "3.2"
services: 
    proxy:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./proxy
        ports:
            - "3050:80"
        networks:
            - app-network
        hostname: proxy
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - "PG_HOST=${SHABAM_PG_HOST}"
            - "PG_DATABASE=${SHABAM_PG_DATABASE}"
            - "PG_USER=${SHABAM_PG_USER}"
            - "PG_PORT=${SHABAM_PG_PORT}"
            - "PG_PASSWORD=${SHABAM_PG_PASSWORD}"
            - "JWT_SECRET=${SHABAM_JWT_SECRET}"
            - "JWT_EXPIRE_TIME=${SHABAM_JWT_EXPIRE_TIME}"
        networks:
            - app-network
    client:
        build:
            dockerfile: Dockerfile
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        networks:
            - app-network
    fingerprint_worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./fingerprint_worker
        volumes: 
            - /app/node_modules
            - ./fingerprint_worker:/app
        networks:
            - app-network
    identification_worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./identification_worker
        volumes: 
            - /app/node_modules
            - ./identification_worker:/app
        networks:
            - app-network
networks:
    app-network:
