#!/bin/bash

function build() {
  bash ./scripts/build.sh
}

function start:it--metadata() {
  bash ./scripts/start_it.sh 'db-metadata' postgres postgres development 5432;
}

function start:psql--metadata() {
  bash ./scripts/start_psql.sh 'db-metadata' postgres postgres development 5432;
}

function exec:init-schema--metadata() {
  bash ./scripts/actions/init_metadata_db.sh false;
}

function exec:init-schema--address-all() {
  bash ./scripts/actions/init_all_address_dbs.sh 3 false;
}

function exec:init-schema--address-0() {
  bash ./scripts/actions/init_address_db.sh 0 false;
}

function exec:init-schema--address-1() {
  bash ./scripts/actions/init_address_db.sh 1 false
}

function exec:init-schema--address-2() {
  bash ./scripts/actions/init_address_db.sh 2 false
}

# Run a function name in the context of this script
eval "$@"