FROM ubuntu:20.04

WORKDIR /core-lib

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
  apt-get install -y curl build-essential autotools-dev automake

# Install node
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash 
RUN apt-get install nodejs

# Install liquid-dsp
COPY ./liquid-dsp ./liquid-dsp
WORKDIR /core-lib/liquid-dsp
RUN ./bootstrap.sh && ./configure && make && make install

WORKDIR /core-lib

RUN npm install -g node-gyp

COPY package*.json .
RUN npm install

ENTRYPOINT ["tail", "-f", "/dev/null"]