FROM ubuntu:22.04

WORKDIR /core-lib

ENV DEBIAN_FRONTEND noninteractive

# General dependencies
RUN apt-get update && \
  apt-get install -y curl build-essential cmake

# liquid-dsp dependencies
RUN apt-get install -y automake libfftw3-dev

ENTRYPOINT ["tail", "-f", "/dev/null"]